-- MySQL Script generated by MySQL Workbench
-- Fri Jun 17 14:24:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema roeiplanner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `#__persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__genders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__natural_persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__natural_persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NULL,
  `first_name` VARCHAR(255) NULL,
  `middle_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `gender` INT UNSIGNED NULL,
  `date_of_birth` DATE NULL,
  `user_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `gender_idx` (`gender` ASC),
  CONSTRAINT `natural_persons_gender`
    FOREIGN KEY (`gender`)
    REFERENCES `#__genders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__legal_persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__legal_persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `full_name` VARCHAR(255) NULL,
  `short_name` VARCHAR(255) NULL,
  `sort_name` VARCHAR(255) NULL,
  `website` VARCHAR(255) NULL,
  `date_of_incorporation` DATE NULL,
  `closing_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_idx` (`person_id` ASC),
  CONSTRAINT `legal_persons_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `#__persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__addresses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_id` INT NULL,
  `postal_code` VARCHAR(255) NULL,
  `house_number` VARCHAR(255) NULL,
  `house_number_extension` VARCHAR(255) NULL,
  `street` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__countries` (
  `id` INT NOT NULL,
  `alpha-2` CHAR(2) NOT NULL,
  `alpha-3` CHAR(3) NULL,
  `country_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `alpha-2_UNIQUE` (`alpha-2` ASC),
  UNIQUE INDEX `alpha-3_UNIQUE` (`alpha-3` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__classes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__objects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__objects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `class_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `class_id_idx` (`class_id` ASC),
  CONSTRAINT `objects_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `#__classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__properties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `class_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `class_id_idx` (`class_id` ASC),
  CONSTRAINT `propersties_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `#__classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__property_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__property_values` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `property_id` INT UNSIGNED NOT NULL,
  `object_id` INT UNSIGNED NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `object_id_idx` (`object_id` ASC),
  INDEX `property_id_idx` (`property_id` ASC),
  CONSTRAINT `property_values_property_id`
    FOREIGN KEY (`property_id`)
    REFERENCES `#__properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `property_values_object_id`
    FOREIGN KEY (`object_id`)
    REFERENCES `#__objects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__is_member_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__is_member_of` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `legal_person_id` INT UNSIGNED NOT NULL,
  `membership_id` VARCHAR(255) NULL,
  `since` DATE NULL,
  `until` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `legal_person_id_idx` (`legal_person_id` ASC),
  INDEX `person_id_idx` (`person_id` ASC),
  CONSTRAINT `is_member_of_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `#__persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `is_member_of_legal_person_id`
    FOREIGN KEY (`legal_person_id`)
    REFERENCES `#__legal_persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__is_owner_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__is_owner_of` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `object_id` INT UNSIGNED NOT NULL,
  `since` DATE NULL,
  `until` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_idx` (`person_id` ASC),
  INDEX `object_id_idx` (`object_id` ASC),
  CONSTRAINT `is_owner_of_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `#__persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `is_owner_of_object_id`
    FOREIGN KEY (`object_id`)
    REFERENCES `#__objects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `start` DATETIME NULL,
  `finish` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__has_address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  `since` DATE NULL,
  `until` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_idx` (`person_id` ASC),
  INDEX `address_id_idx` (`address_id` ASC),
  CONSTRAINT `has_address_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `#__persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `has_address_address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `#__addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__questionnaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__questionnaires` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__answer_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__answer_lists` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__answer_list_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__answer_list_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `answer_list_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `answer_list_id_idx` (`answer_list_id` ASC),
  CONSTRAINT `answer_list_items_answer_list_id`
    FOREIGN KEY (`answer_list_id`)
    REFERENCES `#__answer_lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__questions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `questionnaire_id` INT UNSIGNED NOT NULL,
  `answer_list_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `questionnaire_id_idx` (`questionnaire_id` ASC),
  INDEX `answer_list_id_idx` (`answer_list_id` ASC),
  CONSTRAINT `questions_questionnaire_id`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `#__questionnaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questions_answer_list_id`
    FOREIGN KEY (`answer_list_id`)
    REFERENCES `#__answer_lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__responses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `question_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_idx` (`person_id` ASC),
  INDEX `question_id_idx` (`question_id` ASC),
  CONSTRAINT `responses_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `#__persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `responses_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `#__questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__reservations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `natural_person_id` INT UNSIGNED NOT NULL,
  `object_id` INT UNSIGNED NOT NULL,
  `from` DATETIME NULL,
  `until` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `natural_person_id_idx` (`natural_person_id` ASC),
  INDEX `object_id_idx` (`object_id` ASC),
  CONSTRAINT `reservations_natural_person_id`
    FOREIGN KEY (`natural_person_id`)
    REFERENCES `#__natural_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reservations_object_id`
    FOREIGN KEY (`object_id`)
    REFERENCES `#__objects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__functions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__functions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `legal_person_id` INT UNSIGNED NOT NULL,
  `function_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `legal_person_id_idx` (`legal_person_id` ASC),
  CONSTRAINT `functions_legal_person_id`
    FOREIGN KEY (`legal_person_id`)
    REFERENCES `#__legal_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__has_function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__has_function` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `natural_person_id` INT UNSIGNED NOT NULL,
  `function_id` INT UNSIGNED NOT NULL,
  `from` DATE NULL,
  `until` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `natural_person_id_idx` (`natural_person_id` ASC),
  INDEX `function_id_idx` (`function_id` ASC),
  CONSTRAINT `has_function_natural_person_id`
    FOREIGN KEY (`natural_person_id`)
    REFERENCES `#__natural_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `has_function_function_id`
    FOREIGN KEY (`function_id`)
    REFERENCES `#__functions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__licenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__licenses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `legal_person_id` INT UNSIGNED NOT NULL,
  `license_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `legal_person_id_idx` (`legal_person_id` ASC),
  CONSTRAINT `licenses_legal_person_id`
    FOREIGN KEY (`legal_person_id`)
    REFERENCES `#__legal_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__has_license`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__has_license` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `license_id` INT UNSIGNED NOT NULL,
  `from` DATE NULL,
  `until` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `license_id_idx` (`license_id` ASC),
  INDEX `person_id_idx` (`person_id` ASC),
  CONSTRAINT `has_license_license_id`
    FOREIGN KEY (`license_id`)
    REFERENCES `#__licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `has_license_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `#__persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__relations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__relations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `relation` VARCHAR(255) NULL,
  `counter_relation` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__has_relation_with`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__has_relation_with` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id_source` INT UNSIGNED NOT NULL,
  `person_id_target` INT UNSIGNED NOT NULL,
  `relation_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `person_source_id_idx` (`person_id_source` ASC),
  INDEX `person_target_id_idx` (`person_id_target` ASC),
  INDEX `relation_id_idx` (`relation_id` ASC),
  CONSTRAINT `has_relation_with_person_id_source`
    FOREIGN KEY (`person_id_source`)
    REFERENCES `#__natural_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `has_relation_with_person_id_target`
    FOREIGN KEY (`person_id_target`)
    REFERENCES `#__natural_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `has_relation_with_relation_id`
    FOREIGN KEY (`relation_id`)
    REFERENCES `#__relations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__bank_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__bank_accounts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `iban` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__has_bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__has_bank_account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `bank_account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_idx` (`person_id` ASC),
  INDEX `bank_account_id_idx` (`bank_account_id` ASC),
  CONSTRAINT `has_bank_account_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `#__persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `has_bank_account_bank_account_id`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `#__bank_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__invoices` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id_from` INT UNSIGNED NOT NULL,
  `person_id_to` INT UNSIGNED NOT NULL,
  `invoice_number` VARCHAR(255) NULL,
  `invoice_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_from_idx` (`person_id_from` ASC),
  INDEX `person_id_to_idx` (`person_id_to` ASC),
  CONSTRAINT `invoices_person_id_from`
    FOREIGN KEY (`person_id_from`)
    REFERENCES `#__persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoices_person_id_to`
    FOREIGN KEY (`person_id_to`)
    REFERENCES `#__persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__invoice_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__invoice_lines` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_id` INT UNSIGNED NOT NULL,
  `invoice_line` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `invoice_id_idx` (`invoice_id` ASC),
  CONSTRAINT `invoice_lines_invoice_id`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `#__invoices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__training_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__training_plans` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_by` INT UNSIGNED NOT NULL,
  `created_on` DATETIME NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `created_by_idx` (`created_by` ASC),
  CONSTRAINT `training_plans_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `#__natural_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `#__persons`
-- -----------------------------------------------------

INSERT INTO `#__persons` (`id`) VALUES (1);
INSERT INTO `#__persons` (`id`) VALUES (2);
INSERT INTO `#__persons` (`id`) VALUES (3);
INSERT INTO `#__persons` (`id`) VALUES (4);
INSERT INTO `#__persons` (`id`) VALUES (5);
INSERT INTO `#__persons` (`id`) VALUES (6);
INSERT INTO `#__persons` (`id`) VALUES (7);
INSERT INTO `#__persons` (`id`) VALUES (8);
INSERT INTO `#__persons` (`id`) VALUES (9);
INSERT INTO `#__persons` (`id`) VALUES (10);
INSERT INTO `#__persons` (`id`) VALUES (11);
INSERT INTO `#__persons` (`id`) VALUES (12);
INSERT INTO `#__persons` (`id`) VALUES (13);
INSERT INTO `#__persons` (`id`) VALUES (14);
INSERT INTO `#__persons` (`id`) VALUES (15);
INSERT INTO `#__persons` (`id`) VALUES (16);
INSERT INTO `#__persons` (`id`) VALUES (17);
INSERT INTO `#__persons` (`id`) VALUES (18);
INSERT INTO `#__persons` (`id`) VALUES (19);
INSERT INTO `#__persons` (`id`) VALUES (20);
INSERT INTO `#__persons` (`id`) VALUES (21);
INSERT INTO `#__persons` (`id`) VALUES (22);
INSERT INTO `#__persons` (`id`) VALUES (23);
INSERT INTO `#__persons` (`id`) VALUES (24);
INSERT INTO `#__persons` (`id`) VALUES (25);
INSERT INTO `#__persons` (`id`) VALUES (26);
INSERT INTO `#__persons` (`id`) VALUES (27);
INSERT INTO `#__persons` (`id`) VALUES (28);
INSERT INTO `#__persons` (`id`) VALUES (29);
INSERT INTO `#__persons` (`id`) VALUES (30);
INSERT INTO `#__persons` (`id`) VALUES (31);
INSERT INTO `#__persons` (`id`) VALUES (32);
INSERT INTO `#__persons` (`id`) VALUES (33);
INSERT INTO `#__persons` (`id`) VALUES (34);
INSERT INTO `#__persons` (`id`) VALUES (35);
INSERT INTO `#__persons` (`id`) VALUES (36);
INSERT INTO `#__persons` (`id`) VALUES (37);
INSERT INTO `#__persons` (`id`) VALUES (38);
INSERT INTO `#__persons` (`id`) VALUES (39);
INSERT INTO `#__persons` (`id`) VALUES (40);
INSERT INTO `#__persons` (`id`) VALUES (41);
INSERT INTO `#__persons` (`id`) VALUES (42);
INSERT INTO `#__persons` (`id`) VALUES (43);
INSERT INTO `#__persons` (`id`) VALUES (44);
INSERT INTO `#__persons` (`id`) VALUES (45);
INSERT INTO `#__persons` (`id`) VALUES (46);
INSERT INTO `#__persons` (`id`) VALUES (47);
INSERT INTO `#__persons` (`id`) VALUES (48);
INSERT INTO `#__persons` (`id`) VALUES (49);
INSERT INTO `#__persons` (`id`) VALUES (50);
INSERT INTO `#__persons` (`id`) VALUES (51);
INSERT INTO `#__persons` (`id`) VALUES (52);
INSERT INTO `#__persons` (`id`) VALUES (53);
INSERT INTO `#__persons` (`id`) VALUES (54);
INSERT INTO `#__persons` (`id`) VALUES (55);
INSERT INTO `#__persons` (`id`) VALUES (56);
INSERT INTO `#__persons` (`id`) VALUES (57);
INSERT INTO `#__persons` (`id`) VALUES (58);
INSERT INTO `#__persons` (`id`) VALUES (59);
INSERT INTO `#__persons` (`id`) VALUES (60);
INSERT INTO `#__persons` (`id`) VALUES (61);
INSERT INTO `#__persons` (`id`) VALUES (62);
INSERT INTO `#__persons` (`id`) VALUES (63);
INSERT INTO `#__persons` (`id`) VALUES (64);
INSERT INTO `#__persons` (`id`) VALUES (65);
INSERT INTO `#__persons` (`id`) VALUES (66);
INSERT INTO `#__persons` (`id`) VALUES (67);
INSERT INTO `#__persons` (`id`) VALUES (68);
INSERT INTO `#__persons` (`id`) VALUES (69);
INSERT INTO `#__persons` (`id`) VALUES (70);
INSERT INTO `#__persons` (`id`) VALUES (71);
INSERT INTO `#__persons` (`id`) VALUES (72);
INSERT INTO `#__persons` (`id`) VALUES (73);
INSERT INTO `#__persons` (`id`) VALUES (74);
INSERT INTO `#__persons` (`id`) VALUES (75);
INSERT INTO `#__persons` (`id`) VALUES (76);
INSERT INTO `#__persons` (`id`) VALUES (77);
INSERT INTO `#__persons` (`id`) VALUES (78);
INSERT INTO `#__persons` (`id`) VALUES (79);
INSERT INTO `#__persons` (`id`) VALUES (80);
INSERT INTO `#__persons` (`id`) VALUES (81);
INSERT INTO `#__persons` (`id`) VALUES (82);
INSERT INTO `#__persons` (`id`) VALUES (83);
INSERT INTO `#__persons` (`id`) VALUES (84);
INSERT INTO `#__persons` (`id`) VALUES (85);
INSERT INTO `#__persons` (`id`) VALUES (86);
INSERT INTO `#__persons` (`id`) VALUES (87);
INSERT INTO `#__persons` (`id`) VALUES (88);
INSERT INTO `#__persons` (`id`) VALUES (89);
INSERT INTO `#__persons` (`id`) VALUES (90);
INSERT INTO `#__persons` (`id`) VALUES (91);
INSERT INTO `#__persons` (`id`) VALUES (92);
INSERT INTO `#__persons` (`id`) VALUES (93);
INSERT INTO `#__persons` (`id`) VALUES (94);
INSERT INTO `#__persons` (`id`) VALUES (95);
INSERT INTO `#__persons` (`id`) VALUES (96);
INSERT INTO `#__persons` (`id`) VALUES (97);
INSERT INTO `#__persons` (`id`) VALUES (98);
INSERT INTO `#__persons` (`id`) VALUES (99);
INSERT INTO `#__persons` (`id`) VALUES (100);
INSERT INTO `#__persons` (`id`) VALUES (101);
INSERT INTO `#__persons` (`id`) VALUES (102);
INSERT INTO `#__persons` (`id`) VALUES (103);
INSERT INTO `#__persons` (`id`) VALUES (104);
INSERT INTO `#__persons` (`id`) VALUES (105);
INSERT INTO `#__persons` (`id`) VALUES (106);
INSERT INTO `#__persons` (`id`) VALUES (107);
INSERT INTO `#__persons` (`id`) VALUES (108);
INSERT INTO `#__persons` (`id`) VALUES (109);
INSERT INTO `#__persons` (`id`) VALUES (110);
INSERT INTO `#__persons` (`id`) VALUES (111);
INSERT INTO `#__persons` (`id`) VALUES (112);
INSERT INTO `#__persons` (`id`) VALUES (113);
INSERT INTO `#__persons` (`id`) VALUES (114);
INSERT INTO `#__persons` (`id`) VALUES (115);
INSERT INTO `#__persons` (`id`) VALUES (116);
INSERT INTO `#__persons` (`id`) VALUES (117);
INSERT INTO `#__persons` (`id`) VALUES (118);
INSERT INTO `#__persons` (`id`) VALUES (119);




-- -----------------------------------------------------
-- Data for table `#__genders`
-- -----------------------------------------------------

INSERT INTO `#__genders` (`id`, `gender`) VALUES (1, 'COM_ROEIPLANNER_FEMALE');
INSERT INTO `#__genders` (`id`, `gender`) VALUES (2, 'COM_ROEIPLANNER_MALE');
INSERT INTO `#__genders` (`id`, `gender`) VALUES (3, 'COM_ROEIPLANNER_NON_BINARY');
INSERT INTO `#__genders` (`id`, `gender`) VALUES (4, 'COM_ROEIPLANNER_TRANSGENDER');
INSERT INTO `#__genders` (`id`, `gender`) VALUES (5, 'COM_ROEIPLANNER_INTERSEXUAL');
INSERT INTO `#__genders` (`id`, `gender`) VALUES (6, 'COM_ROEIPLANNER_I_PREFER_NOT_TO_SAY');
INSERT INTO `#__genders` (`id`, `gender`) VALUES (7, 'COM_ROEIPLANNER_LET_ME_TYPE');




-- -----------------------------------------------------
-- Data for table `#__legal_persons`
-- -----------------------------------------------------

INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (1, 1, 'Koninklijke Nederlandse Roeibond', 'KNRB', 'KNRB', 'https://knrb.nl/', NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (2, 2, 'Alkmaarsche Roei- en Zeilvereniging', 'ARZV-R', 'Alkmaarsche Roeivereniging', 'https://roei.arzv.nl/', '1910-04-19', NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (3, 3, 'Haerlemsche Studenten Roeivereniging Amphitrite', 'Amphitrite', 'Amphitrite', 'https://amphitrite.nl', '1990-10-31', NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (4, 4, 'Roei- en zeilvereniging de Amstel', 'De Amstel', 'Amstel', 'https://amstelroei.nl', '1874-09-11', NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (5, 5, 'Roeivereniging de Drietand', 'De Drietand', 'Drietand', '', '1930-09-30', NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (6, 6, 'Koninklijke Amsterdamsche  roei- en zeilvereniging de Hoop', 'De Hoop', 'Hoop', 'https://karzvdehoop.nl', '1848-05-26', NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (7, 7, 'Koninklijke Nederlandsche Zeil- & Roeivereniging', 'KNZ&RV', 'Koninklijke', 'https://www.knzrv.nl/', NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (8, 8, 'Roeivereniging De Kogge', 'De Kogge', 'Kogge', 'https://rvdekogge.nl/', NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (9, 9, 'Minerva', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (10, 10, 'Naarden', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (11, 11, 'Nereus', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (12, 12, 'Okeanos', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (13, 13, 'Ossa', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (14, 14, 'Panta Rhei', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (15, 15, 'Poseidon', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (16, 16, 'RIC', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (17, 17, 'Het Spaarne', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (18, 18, 'Stern', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (19, 19, 'Where', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (20, 20, 'Willem III', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (21, 21, 'Zaan', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (22, 22, 'Zaankanaries', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (23, 23, 'ZZV Roeien', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (24, 24, 'Alphen', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (25, 25, 'Asopos de Vliet', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (26, 26, 'Barendrecht', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (27, 27, 'Binnenmaas', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (28, 28, 'DDS', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (29, 29, 'Gorcumse', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (30, 30, 'Gouda', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (31, 31, 'Iris', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (32, 32, 'De Laak', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (33, 33, 'Laga', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (34, 34, 'Die Leythe', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (35, 35, 'De Maas', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (36, 36, 'Meije', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (37, 37, 'Nautilus', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (38, 38, 'Njord', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (39, 39, 'Oostvoorne', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (40, 40, 'Pelargos', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (41, 41, 'Proteus-Eretes', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (42, 42, 'Rijnland', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (43, 43, 'Rijnmond', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (44, 44, 'Skadi', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (45, 45, 'Agon', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (46, 46, 'Amenophis', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (47, 47, 'Argo', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (48, 48, 'Doorslag', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (49, 49, 'Eem', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (50, 50, 'Galjoen', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (51, 51, 'Helling', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (52, 52, 'Hemus', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (53, 53, 'Hollandia', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (54, 54, 'Leerdam', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (55, 55, 'Pampus', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (56, 56, 'Triton', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (57, 57, 'UR&KV Michiel de Ruyter', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (58, 58, 'VADA', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (59, 59, 'Viking', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (60, 60, 'Weesp', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (61, 61, 'Aegir', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (62, 62, 'Aengwirden', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (63, 63, 'Asser Roeiclub', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (64, 64, 'Diep', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (65, 65, 'Dragt', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (66, 66, 'Epsilon', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (67, 67, 'Geeuw', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (68, 68, 'Groninger Roeibond', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (69, 69, 'Gyas', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (70, 70, 'Hunze', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (71, 71, 'Neptunus', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (72, 72, 'Skylla', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (73, 73, 'Wetterwille', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (74, 74, 'Amycus', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (75, 75, 'Anker', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (76, 76, 'Boreas', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (77, 77, 'Daventria', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (78, 78, 'De Ank', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (79, 79, 'Euros', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (80, 80, 'Grift', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (81, 81, 'IJssel', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (82, 82, 'Isala', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (83, 83, 'Jason', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (84, 84, 'Phocas', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (85, 85, 'Pontos', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (86, 86, 'Salland', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (87, 87, 'Thyro', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (88, 88, 'Tubantia', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (89, 89, 'De Waal', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (90, 90, 'Zwolsche R&ZV', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (91, 91, 'Aeneas', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (92, 92, 'AROSS', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (93, 93, 'Beatrix', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (94, 94, 'Breda', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (95, 95, 'Dudok van Heel', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (96, 96, 'Hertog', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (97, 97, 'Honte', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (98, 98, 'MWC', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (99, 99, 'Odin', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (100, 100, 'De Drie Provinciën', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (101, 101, 'Saurus', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (102, 102, 'Scaldis', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (103, 103, 'Vidar', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (104, 104, 'Weert', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (105, 105, 'De Kop', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (106, 106, 'De Krom', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (107, 107, 'Dordrecht', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (108, 108, 'De Compagnie', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (109, 109, 'KWVL', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (110, 110, 'Roosendaalse', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (111, 111, 'Scheveningsche', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (112, 112, 'Skøll', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (113, 113, 'Thêta', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (114, 114, 'Tilburgse', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (115, 115, 'Cornelis Tromp', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (116, 116, 'Voorne-Putten', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (117, 117, 'Zeeuws-Vlaanderen', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (118, 118, 'Zuidelijke Roeibond', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (119, 119, 'Amsterdamsche Roeibond', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `#__legal_persons` (`id`, `person_id`, `full_name`, `short_name`, `sort_name`, `website`, `date_of_incorporation`, `closing_date`) VALUES (120, 120, 'Koninklijke Nederlandsche Studenten Roeibond', 'K.N.S.R.B.', 'KNSRB', 'http://www.knsrb.nl/', NULL, NULL);




-- -----------------------------------------------------
-- Data for table `#__addresses`
-- -----------------------------------------------------

INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (1, 528, '1822 AA', '1', '', 'Beverdam', 'Alkmaar');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (2, 528, '1358 AJ', '7', '', 'Verlaatweg', 'Almere');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (3, 528, '3813 TE', '11', '', 'Bernard de Roijstraat', 'Amersfoort');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (4, 528, '1186 DG', '1', '', 'Branding', 'Amstelveen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (5, 528, '1078 RT', '130', '', 'Amsteldijk', 'Amsterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (6, 528, '1091 EH', '1046', '', 'Weesperzijde', 'Amsterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (7, 528, '1096 CN', '4', '', 'Jan Vroegopsingel', 'Amsterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (8, 528, '1077 CJ', '1', '', 'Olympiaplein', 'Amsterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (9, 528, '6827 AW', '92', '', 'Westervoortsedijk', 'Arnhem');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (10, 528, '7332 BD', '130', '', 'Kanaal Zuid', 'Apeldoorn');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (11, 528, '8471 ZZ', '46', '', 'Schuttevaerstraat', 'Bergen Op Zoom');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (12, 528, '3602 AC', '3', '', 'Zandweg', 'Breukelen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (13, 528, '2611 WN', '140', '', 'Oostplantsoen', 'Delft');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (14, 528, '2611 RR', '53', '', 'Nieuwelaan', 'Delft');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (15, 528, '2516 BC', '285', '', 'Binckhorstlaan', 'Den Haag');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (16, 528, '1781 AD', '34', '', 'Het Nieuwe Diep', 'Den Helder');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (17, 528, '7006 GA', '2', '', 'Stokhorstweg', 'Doetinchem');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (18, 528, '3312 AV', '2', '', 'Wantijpark', 'Dordrecht');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (19, 528, '5645 TA', '50', '', 'Kanaaldijk-Zuid', 'Eindhoven');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (20, 528, '7547 AN', '99', '', 'Auke Vleerstraat', 'Enschede');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (21, 528, '4463 AD', '1', '', 'Westhavendijk', 'Goes');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (22, 528, '7783 DB', '2', '', 'Kanaaldijk West', 'Gramsbergen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (23, 528, '9727 GH', '199', '', 'Hoornsediep WZ', 'Groningen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (24, 528, '2034 JA', '101', '', 'Noord-Schalkwijkerweg', 'Haarlem');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (25, 528, '2031 AK', '3', '', 'Mooie Nelpad', 'Haarlem');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (26, 528, '1704 AK', '12', '', 'Westdijk', 'Heerhugowaard');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (27, 528, '1216 CH', '56', '', 'Vreelandseweg', 'Hilversum');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (28, 528, '7909 HV', '1', '', 'Echtenseweg', 'Hoogeveen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (29, 528, '5433 NM', '7', '', 'Keersluisweg', 'Katwijk');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (30, 528, '8938 AK', '13', '', 'Avondsterweg', 'Leeuwarden');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (31, 528, '2332 ES', '182', '', 'Morsweg', 'Leiden');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (32, 528, '2266 GN', '63', '', 'Oostvlietweg', 'Leidschendam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (33, 528, '8225 SZ', '33', '', 'Griend', 'Lelystad');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (34, 528, '2162 VW', '23', '', 'Ruishoornlaan', 'Lisse');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (35, 528, '6219 AC', '24', '', 'Bosscherweg', 'Maastricht');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (36, 528, '4332 AJ', '2', '', 'Havendijk', 'Middelburg');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (37, 528, '1398 BB', '7', '', 'Westzeedijk', 'Muiden');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (38, 528, '3433 PN', '1', '', 'Utrechthaven', 'Nieuwegein');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (39, 528, '6534 AK', '1', '', 'Oostkanaaldijk', 'Nijmegen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (40, 528, '5367 NE', '13', '', 'Ossestraat', 'Macharen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (41, 528, '2811 HS', '35', '', 'Notaris d\'Aumerielaan', 'Reeuwijk');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (42, 528, '4703 RV', '60', '', 'Vlietweg', 'Roosendaal');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (43, 528, '3063NG ', '3', '', 'Plantagelaan', 'Rotterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (44, 528, '3054 XM', '93', '', 'Prinsemolenpad', 'Rotterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (45, 528, '5211 XB', '28', '', 'Citadellaan', 'Den Bosch');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (46, 528, '8601 GW', '1', '', 'Malta', 'Sneek');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (47, 528, '4532 LR', '45', '', 'Serlippenstraat', 'Terneuzen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (48, 528, '5081 NJ', '9', '', 'Beekse Bergen', 'Hilvarenbeek');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (49, 528, '1423 BZ', '253', '', 'Amsteldijk-Zuid', 'Uithoorn');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (50, 528, '3525 BB', '13', '', 'Verlengde Hoogravenseweg', 'Utrecht');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (51, 528, '6702 PB', '59', '', 'Grebbedijk', 'Wageningen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (52, 528, '6006 SJ', '50', '', 'Industriekade', 'Weert');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (53, 528, '1693 HM', '15', '', 'Dirk Bijvoetweg', 'Wervershoof');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (54, 528, '1506 PK', '70', '', 'Havenstraat', 'Zaandam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (55, 528, '3899 XS', '4', '', 'Baardmeesweg', 'Zeewolde');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (56, 528, '3238 LM', '1', '', 'Kanaaldijk West', 'Zwartewaal');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (57, 528, '8017 LJ', '100', '', 'Holtenbroekerdijk', 'Zwolle');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (58, 528, '7604 PN', '22', '', 'Badweg', 'Almelo');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (59, 528, '1301 AH', '10329', '', 'Postbus', 'Almere');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (60, 528, '1182 AG', '8', '', 'Bosbaan', 'Amstelveen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (61, 528, '1096 AC', '32', '', 'Korte Ouderkerkerdijk', 'Amsterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (62, 528, '1096 CN', '6', '', 'Jan Vroegopsingel', 'Amsterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (63, 528, '1071 XW', '122', '', 'Hobbemakade', 'Amsterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (64, 528, '1096 CN', '8', '', 'Jan Vroegopsingel', 'Amsterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (65, 528, '9902 BW', '100', '', 'Farmsumerweg', 'Appingedam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (66, 528, '9409 TV', '31', '', 'Kanaaldijk', 'Assen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (67, 528, '7361 GR', '21', '', 'Reeënbergweg', 'Beekbergen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (68, 528, '8398 GK', '23', '', 'Markeweg', 'Blesdijke');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (69, 528, '3620 AC', '130', '', 'Postbus', 'Breukelen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (70, 528, '1781 AC', '8', '', 'Het Nieuwe Diep', 'Den Helder');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (71, 528, '3312AV ', '2', '', 'Wantijpark', 'Ordrecht');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (72, 528, '5600 AV', '817', '', 'Postbus', 'Eindhoven');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (73, 528, '9701 BK', '1438', '', 'Postbus', 'Groningen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (74, 528, '2034 JA', '101', '', 'Noord Schalkwijkerweg', 'Haarlem');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (75, 528, '2102 AC', '5', '', 'Marisplein', 'Heemstede');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (76, 528, '8267BA ', '3', '', 'Seveningseweg', 'Ampen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (77, 528, '4142 LD', '27', '', 'Lingedijk', 'Leerdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (78, 528, '2312 VW', '34', '', 'Van der Werfstraat', 'Leiden');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (79, 528, '6200 AD', '175', '', 'Postbus', 'Maastricht');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (80, 528, '4331 AB', '1', '', 'Bachtensteene', 'Middelburg');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (81, 528, '3270 AA', '5521', '', 'Postbus', 'Mijnsheerenland');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (82, 528, '1411 EW', '1', '', 'Thierensweg', 'Naarden');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (83, 528, '2420 AB', '56', '', 'Postbus', 'Nieuwkoop');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (84, 528, '3233 ZG', '318', '', 'Postbus', 'Oostvoorne');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (85, 528, '1440 AG', '257', '', 'Postbus', 'Purmerend');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (86, 528, '6041 TL', '52', '', 'De Weerd', 'Roermond');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (87, 528, '2991 VH', '73', '', 'Noldijk', 'Barendrecht');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (88, 528, '3037 AV', '20', '', 'Noorderkanaalweg', 'Rotterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (89, 528, '3034 NC', '100', '', 'Crooswijkse Bocht', 'Rotterdam');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (90, 528, '1741 NV', '6', '', 'Westerweg', 'Schagen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (91, 528, '4844 CL', '30', '', 'Bredaseweg', 'Terheijden');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (92, 528, '5004 BB', '1085', '', 'Postbus', 'Tilburg');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (93, 528, '8334 TP', '2', '', 'Hooidijk', 'Tuk');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (94, 528, '6702 DV', '1', '', 'Jachthaven', 'Wageningen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (95, 528, '1381 GR', '17', '', 'Utrechtseweg', 'Weesp');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (96, 528, '3449 HS', '154', '', 'Barwoutswaarder', 'Woerden');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (97, 528, '3891 ZN', '61', '', 'Almereweg', 'Zeewolde');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (98, 528, '8031 LJ', '100', '', 'Holtenbroekerdijk', 'Zwolle');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (99, 528, NULL, '10', NULL, 'Bosbaan', 'Amstelveen');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (100, 528, '1398 BB', '7', NULL, 'Westzeedijk', 'Muiden');
INSERT INTO `#__addresses` (`id`, `country_id`, `postal_code`, `house_number`, `house_number_extension`, `street`, `city`) VALUES (101, 528, '1079 JB', '85', '2', 'Vechtstraat', 'Amsterdam');




-- -----------------------------------------------------
-- Data for table `#__countries`
-- -----------------------------------------------------

INSERT INTO `#__countries` (`id`, `alpha-2`, `alpha-3`, `country_name`) VALUES (528, 'NL', 'NLD', 'COM_ROEIPLANNER_THE_NETHERLANDS');




-- -----------------------------------------------------
-- Data for table `#__is_member_of`
-- -----------------------------------------------------

INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (1, 2, 1, 'KNRB0044', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (2, 3, 1, 'KNRB0024', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (3, 4, 1, 'KNRB0046', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (4, 5, 1, 'KNRB0070', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (5, 6, 1, 'KNRB0025', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (6, 7, 1, 'KNRB0028', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (7, 8, 1, 'KNRB8863', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (8, 9, 1, 'KNRB0081', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (9, 10, 1, 'KNRB0052', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (10, 11, 1, 'KNRB0008', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (11, 12, 1, 'KNRB0056', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (12, 13, 1, 'KNRB0085', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (13, 14, 1, 'KNRB0005', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (14, 15, 1, 'KNRB0053', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (15, 16, 1, 'KNRB0089', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (16, 17, 1, 'KNRB0032', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (17, 18, 1, 'KNRB0076', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (18, 19, 1, 'KNRB0077', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (19, 20, 1, 'KNRB0100', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (20, 21, 1, 'KNRB0110', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (21, 22, 1, 'KNRB0119', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (22, 23, 1, 'KNRB0117', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (23, 24, 1, 'KNRB0060', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (24, 25, 1, 'KNRB0003', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (25, 26, 1, 'KNRB0062', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (26, 27, 1, 'KNRB1522', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (27, 28, 1, 'KNRB0067', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (28, 29, 1, 'KNRB0047', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (29, 30, 1, 'KNRB0048', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (30, 31, 1, 'KNRB9529', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (31, 32, 1, 'KNRB0074', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (32, 33, 1, 'KNRB0015', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (33, 34, 1, 'KNRB0036', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (34, 35, 1, 'KNRB0031', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (35, 36, 1, 'KNRB0075', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (36, 37, 1, 'KNRB0082', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (37, 38, 1, 'KNRB0033', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (38, 39, 1, 'KNRB0114', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (39, 40, 1, 'KNRB4017', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (40, 41, 1, 'KNRB0088', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (41, 42, 1, 'KNRB0090', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (42, 43, 1, 'KNRB0091', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (43, 44, 1, 'KNRB0006', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (44, 45, 1, 'KNRB0123', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (45, 46, 1, 'KNRB0061', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (46, 47, 1, 'KNRB0111', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (47, 48, 1, 'KNRB4070', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (48, 49, 1, 'KNRB0012', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (49, 50, 1, 'KNRB0084', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (50, 51, 1, 'KNRB0116', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (51, 52, 1, 'KNRB0079', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (52, 53, 1, 'KNRB0034', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (53, 54, 1, 'KNRB0080', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (54, 55, 1, 'KNRB0086', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (55, 56, 1, 'KNRB0108', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (56, 57, 1, 'KNRB0106', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (57, 58, 1, 'KNRB0115', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (58, 59, 1, 'KNRB0107', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (59, 60, 1, 'KNRB0098', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (60, 61, 1, 'KNRB0019', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (61, 62, 1, 'KNRB0058', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (62, 63, 1, 'KNRB0009', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (63, 64, 1, 'KNRB0095', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (64, 65, 1, 'KNRB0068', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (65, 66, 1, 'KNRB0078', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (66, 67, 1, 'KNRB0043', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (67, 68, 1, 'KNRB0017', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (68, 69, 1, 'KNRB0002', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (69, 70, 1, 'KNRB0026', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (70, 71, 1, 'KNRB0035', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (71, 72, 1, 'KNRB0121', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (72, 73, 1, 'KNRB0099', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (73, 74, 1, 'KNRB0104', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (74, 75, 1, 'KNRB0124', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (75, 76, 1, 'KNRB5914', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (76, 77, 1, 'KNRB0045', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (77, 78, 1, 'KNRB0112', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (78, 79, 1, 'KNRB0014', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (79, 80, 1, 'KNRB8268', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (80, 81, 1, 'KNRB0030', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (81, 82, 1, 'KNRB0049', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (82, 83, 1, 'KNRB0050', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (83, 84, 1, 'KNRB0042', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (84, 85, 1, 'KNRB0087', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (85, 86, 1, 'KNRB0094', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (86, 87, 1, 'KNRB0096', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (87, 88, 1, 'KNRB0097', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (88, 89, 1, 'KNRB1129', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (89, 90, 1, 'KNRB0054', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (90, 91, 1, 'KNRB0057', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (91, 92, 1, 'KNRB0007', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (92, 93, 1, 'KNRB0063', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (93, 94, 1, 'KNRB0065', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (94, 95, 1, 'KNRB0066', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (95, 96, 1, 'KNRB0071', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (96, 97, 1, 'KNRB0072', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (97, 98, 1, 'KNRB0037', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (98, 99, 1, 'KNRB0122', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (99, 100, 1, 'KNRB0069', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (100, 101, 1, 'KNRB0038', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (101, 102, 1, 'KNRB0018', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (102, 103, 1, 'KNRB0105', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (103, 104, 1, 'KNRB0101', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (104, 105, 1, 'KNRB9129', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (105, 106, 1, 'KNRB0073', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (106, 107, 1, 'KNRB0051', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (107, 108, 1, 'KNRB8864', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (108, 109, 1, 'KNRB0126', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (109, 110, 1, 'KNRB0092', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (110, 111, 1, 'KNRB0125', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (111, 112, 1, 'KNRB0001', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (112, 113, 1, 'KNRB0016', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (113, 114, 1, 'KNRB0103', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (114, 115, 1, 'KNRB0023', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (115, 116, 1, 'KNRB9454', NULL, NULL);
INSERT INTO `#__is_member_of` (`id`, `person_id`, `legal_person_id`, `membership_id`, `since`, `until`) VALUES (116, 117, 1, 'KNRB0093', NULL, NULL);




-- -----------------------------------------------------
-- Data for table `#__has_address`
-- -----------------------------------------------------

INSERT INTO `#__has_address` (`id`, `person_id`, `address_id`, `since`, `until`) VALUES (1, 1, 99, NULL, NULL);
INSERT INTO `#__has_address` (`id`, `person_id`, `address_id`, `since`, `until`) VALUES (2, 2, 1, NULL, NULL);
INSERT INTO `#__has_address` (`id`, `person_id`, `address_id`, `since`, `until`) VALUES (3, 3, 24, NULL, NULL);
INSERT INTO `#__has_address` (`id`, `person_id`, `address_id`, `since`, `until`) VALUES (4, 4, 63, NULL, NULL);
INSERT INTO `#__has_address` (`id`, `person_id`, `address_id`, `since`, `until`) VALUES (5, 6, 6, NULL, NULL);
INSERT INTO `#__has_address` (`id`, `person_id`, `address_id`, `since`, `until`) VALUES (6, 6, 99, NULL, NULL);




-- -----------------------------------------------------
-- Data for table `#__relations`
-- -----------------------------------------------------

INSERT INTO `#__relations` (`id`, `relation`, `counter_relation`) VALUES (1, 'COM_ROEIPLANNER_PARENT', 'COM_ROEIPLANNER_CHILD');



