-- MySQL Script generated by MySQL Workbench
-- Mon Jun  6 09:49:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP TABLE IF EXISTS `#__persons` ;
DROP TABLE IF EXISTS `#__genders` ;
DROP TABLE IF EXISTS `#__natural_persons` ;
DROP TABLE IF EXISTS `#__legal_persons` ;
DROP TABLE IF EXISTS `#__addresses` ;
DROP TABLE IF EXISTS `#__countries` ;
DROP TABLE IF EXISTS `#__classes` ;
DROP TABLE IF EXISTS `#__objects` ;
DROP TABLE IF EXISTS `#__properties` ;
DROP TABLE IF EXISTS `#__property_values` ;
DROP TABLE IF EXISTS `#__is_member_of` ;
DROP TABLE IF EXISTS `#__is_owner_of` ;
DROP TABLE IF EXISTS `#__events` ;
DROP TABLE IF EXISTS `#__has_address` ;
DROP TABLE IF EXISTS `#__questionnaires` ;
DROP TABLE IF EXISTS `#__answer_lists` ;
DROP TABLE IF EXISTS `#__answer_list_items` ;
DROP TABLE IF EXISTS `#__questions` ;
DROP TABLE IF EXISTS `#__responses` ;
DROP TABLE IF EXISTS `#__reservations` ;
DROP TABLE IF EXISTS `#__functions` ;
DROP TABLE IF EXISTS `#__has_function` ;
DROP TABLE IF EXISTS `#__licenses` ;
DROP TABLE IF EXISTS `#__has_license` ;
DROP TABLE IF EXISTS `#__relations` ;
DROP TABLE IF EXISTS `#__has_relation_with` ;
DROP TABLE IF EXISTS `#__bank_accounts` ;
DROP TABLE IF EXISTS `#__has_bank_account` ;
DROP TABLE IF EXISTS `#__invoices` ;
DROP TABLE IF EXISTS `#__invoice_lines` ;
DROP TABLE IF EXISTS `#__training_plans` ;